import argparse
import csv
import itertools
from pathlib import Path
from statistics import median
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np


ALIGNMENT_CSV = Path(
    "research/analysis/studies/unpruned_phase_differentiation_20260316/phase_seed_alignment.csv"
)
OUT_DIR = Path("results/studies/unpruned_phase_differentiation_20260316")
PRIMARY_DIR = OUT_DIR / "primary"
SUPPLEMENTARY_DIR = OUT_DIR / "supplementary"
PHASES = ["prune0+2", "prune0_only", "prune2_only", "no_prune"]
PHASE_COLORS = {
    "prune0+2": "#e45756",
    "prune0_only": "#f58518",
    "prune2_only": "#54a24b",
    "no_prune": "#4c78a8",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build fixed-run phase comparison plots using paired prune_only phase labels."
    )
    parser.add_argument(
        "--alignment-csv",
        type=Path,
        default=ALIGNMENT_CSV,
        help="Alignment CSV generated by build_unpruned_phase_alignment.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=OUT_DIR,
        help="Output directory for the comparison study package.",
    )
    return parser.parse_args()


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: List[Dict]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def ensure_dirs(paths: Iterable[Path]) -> None:
    for path in paths:
        path.mkdir(parents=True, exist_ok=True)


def active_share_vector(metric_row: Dict[str, str]) -> Tuple[float, float, float]:
    active = np.array([int(metric_row[f"active_{layer_idx}"]) for layer_idx in range(3)], dtype=float)
    total_active = max(float(active.sum()), 1.0)
    shares = active / total_active
    return float(shares[0]), float(shares[1]), float(shares[2])


def share_reallocation_magnitude(
    best_shares: Tuple[float, float, float], final_shares: Tuple[float, float, float]
) -> float:
    deltas = np.abs(np.array(final_shares, dtype=float) - np.array(best_shares, dtype=float))
    return 0.5 * float(deltas.sum())


def collect_rows(alignment_csv: Path) -> List[Dict]:
    rows: List[Dict] = []
    for row in read_csv(alignment_csv):
        phase = row["prune_only_phase"]
        if phase not in PHASES:
            continue
        metrics = read_csv(Path(row["fixed_run"]) / "metrics.csv")
        if not metrics:
            continue

        test_losses = np.array([float(metric["test_loss"]) for metric in metrics], dtype=float)
        train_losses = np.array([float(metric["train_loss"]) for metric in metrics], dtype=float)
        val_losses = np.array([float(metric["val_loss"]) for metric in metrics], dtype=float)
        best_idx = int(np.argmin(val_losses))
        best = metrics[best_idx]
        final = metrics[-1]
        best_shares = active_share_vector(best)
        final_shares = active_share_vector(final)
        final_epoch = int(final["epoch"])
        best_epoch = int(best["epoch"])
        post_best_epochs = final_epoch - best_epoch

        rows.append(
            {
                "phase": phase,
                "seed": int(row["seed"]),
                "run_path": row["fixed_run"],
                "paired_prune_run": row["prune_only_run"],
                "best_epoch": best_epoch,
                "final_epoch": final_epoch,
                "post_best_epochs": post_best_epochs,
                "selected_test_loss": float(test_losses[best_idx]),
                "final_test_loss": float(test_losses[-1]),
                "final_minus_selected": float(test_losses[-1] - test_losses[best_idx]),
                "selected_train_loss": float(train_losses[best_idx]),
                "final_train_loss": float(train_losses[-1]),
                "selected_test_train_gap": float(test_losses[best_idx] - train_losses[best_idx]),
                "final_test_train_gap": float(test_losses[-1] - train_losses[-1]),
                "active_0_best": int(best["active_0"]),
                "active_1_best": int(best["active_1"]),
                "active_2_best": int(best["active_2"]),
                "active_0_final": int(final["active_0"]),
                "active_1_final": int(final["active_1"]),
                "active_2_final": int(final["active_2"]),
                "active_0_drift": int(final["active_0"]) - int(best["active_0"]),
                "active_1_drift": int(final["active_1"]) - int(best["active_1"]),
                "active_2_drift": int(final["active_2"]) - int(best["active_2"]),
                "share_0_best": best_shares[0],
                "share_1_best": best_shares[1],
                "share_2_best": best_shares[2],
                "share_0_final": final_shares[0],
                "share_1_final": final_shares[1],
                "share_2_final": final_shares[2],
                "share_0_drift": final_shares[0] - best_shares[0],
                "share_1_drift": final_shares[1] - best_shares[1],
                "share_2_drift": final_shares[2] - best_shares[2],
                "post_best_share_drift": share_reallocation_magnitude(best_shares, final_shares),
                "post_best_drift_rate": share_reallocation_magnitude(best_shares, final_shares)
                / max(post_best_epochs, 1),
                "share_2_drift_rate": (final_shares[2] - best_shares[2]) / max(post_best_epochs, 1),
                "final_param_count": int(float(final["param_count"])),
            }
        )
    rows.sort(key=lambda item: (PHASES.index(item["phase"]), item["seed"]))
    return rows


def summarize_patterns(rows: Sequence[Dict]) -> List[Dict]:
    keys = [
        "selected_test_loss",
        "final_test_loss",
        "final_minus_selected",
        "best_epoch",
        "post_best_epochs",
        "final_test_train_gap",
        "active_0_best",
        "active_1_best",
        "active_2_best",
        "active_0_final",
        "active_1_final",
        "active_2_final",
        "active_0_drift",
        "active_1_drift",
        "active_2_drift",
        "share_0_best",
        "share_1_best",
        "share_2_best",
        "share_0_final",
        "share_1_final",
        "share_2_final",
        "share_0_drift",
        "share_1_drift",
        "share_2_drift",
        "post_best_share_drift",
        "post_best_drift_rate",
        "share_2_drift_rate",
        "final_param_count",
    ]
    out: List[Dict] = []
    for phase in PHASES:
        group = [row for row in rows if row["phase"] == phase]
        if not group:
            continue
        summary = {"phase": phase, "n": len(group)}
        for key in keys:
            values = [row[key] for row in group]
            summary[f"median_{key}"] = median(values)
        out.append(summary)
    return out


def build_pairwise_stats(rows: Sequence[Dict]) -> List[Dict]:
    metrics = [
        ("selected_test_loss", "selected test loss"),
        ("final_test_loss", "final test loss"),
        ("final_minus_selected", "final minus selected"),
        ("best_epoch", "best epoch"),
        ("final_test_train_gap", "final test-train gap"),
        ("active_1_best", "active layer-1 @ best"),
        ("active_2_best", "active layer-2 @ best"),
        ("active_1_drift", "active layer-1 drift"),
        ("active_2_drift", "active layer-2 drift"),
        ("share_1_drift", "share layer-1 drift"),
        ("share_2_drift", "share layer-2 drift"),
        ("post_best_drift_rate", "post-best drift rate"),
    ]
    pairs = list(itertools.combinations(PHASES, 2))
    out: List[Dict] = []
    for phase_a, phase_b in pairs:
        group_a = [row for row in rows if row["phase"] == phase_a]
        group_b = [row for row in rows if row["phase"] == phase_b]
        if not group_a or not group_b:
            continue
        for key, label in metrics:
            values_a = [row[key] for row in group_a]
            values_b = [row[key] for row in group_b]
            out.append(
                {
                    "metric": key,
                    "label": label,
                    "group_a": phase_a,
                    "group_b": phase_b,
                    "n_group_a": len(values_a),
                    "n_group_b": len(values_b),
                    "median_group_a": median(values_a),
                    "median_group_b": median(values_b),
                    "median_diff_a_minus_b": median(values_a) - median(values_b),
                }
            )
    return out


def _scatter_by_phase(ax, rows: Sequence[Dict], key: str, log_scale: bool = False) -> None:
    phases = [phase for phase in PHASES if any(row["phase"] == phase for row in rows)]
    positions = np.arange(1, len(phases) + 1)
    groups = [[row[key] for row in rows if row["phase"] == phase] for phase in phases]
    bp = ax.boxplot(groups, patch_artist=True, tick_labels=phases, showfliers=False, widths=0.58)
    for patch, phase in zip(bp["boxes"], phases):
        patch.set_facecolor(PHASE_COLORS[phase])
        patch.set_alpha(0.28)
    for pos, phase in zip(positions, phases):
        group = [row for row in rows if row["phase"] == phase]
        jitter = np.linspace(-0.1, 0.1, len(group)) if len(group) > 1 else np.array([0.0])
        for offset, row in zip(jitter, group):
            ax.scatter(
                pos + offset,
                float(row[key]),
                s=52,
                color=PHASE_COLORS[phase],
                edgecolor="white",
                linewidth=0.6,
                zorder=3,
            )
            ax.annotate(
                f"s{row['seed']}",
                (pos + offset, float(row[key])),
                xytext=(3, 3),
                textcoords="offset points",
                fontsize=7,
                color="#444444",
            )
    if log_scale:
        ax.set_yscale("log")
    ax.grid(axis="y", linestyle="--", alpha=0.3)


def plot_phase_assignments(rows: Sequence[Dict], out_path: Path) -> None:
    ordered_rows = sorted(rows, key=lambda row: row["seed"])
    fig, ax = plt.subplots(figsize=(8.8, 1.9))
    positions = np.arange(len(ordered_rows))
    for idx, row in enumerate(ordered_rows):
        ax.scatter(
            idx,
            0,
            s=300,
            marker="s",
            color=PHASE_COLORS[row["phase"]],
            edgecolor="white",
            linewidth=0.8,
        )
    ax.set_xlim(-0.6, len(ordered_rows) - 0.4)
    ax.set_ylim(-0.5, 0.5)
    ax.set_yticks([])
    ax.set_xticks(positions)
    ax.set_xticklabels([f"seed {row['seed']}" for row in ordered_rows])
    ax.set_title("Fixed runs indexed by paired prune_only phase")
    ax.legend(
        handles=[
            plt.Line2D(
                [0],
                [0],
                marker="s",
                linestyle="",
                markersize=10,
                markerfacecolor=PHASE_COLORS[phase],
                markeredgecolor="white",
                label=phase,
            )
            for phase in PHASES
            if any(row["phase"] == phase for row in rows)
        ],
        ncol=3,
        fontsize=8,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.12),
    )
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_endpoint_panels(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(13.6, 4.6))
    panels = [
        ("selected_test_loss", "selected test loss", True),
        ("final_test_loss", "final test loss", True),
        ("final_test_train_gap", "final test-train gap", True),
    ]
    for ax, (key, title, log_scale) in zip(axes, panels):
        _scatter_by_phase(ax, rows, key, log_scale=log_scale)
        ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_speed_panels(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(10.8, 4.6))
    panels = [
        ("best_epoch", "best epoch"),
        ("post_best_epochs", "epochs after best"),
    ]
    for ax, (key, title) in zip(axes, panels):
        _scatter_by_phase(ax, rows, key, log_scale=False)
        ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_best_to_final_degradation(rows: Sequence[Dict], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    _scatter_by_phase(ax, rows, "final_minus_selected", log_scale=True)
    ax.set_ylabel("final test loss - selected test loss")
    ax.set_title("Best-to-final degradation by paired phase")
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_post_best_drift_rate(rows: Sequence[Dict], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    _scatter_by_phase(ax, rows, "post_best_drift_rate", log_scale=False)
    ax.axhline(0.0, color="#666666", linestyle="--", linewidth=1.0)
    ax.set_ylabel("0.5 * L1(share(final)-share(best)) / (final epoch - best epoch)")
    ax.set_title("Post-best drift rate by paired phase")
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_active_drift(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(10.8, 4.6), sharey=True)
    for ax, key, title in zip(
        axes,
        ["active_1_drift", "active_2_drift"],
        ["layer 1", "layer 2"],
    ):
        _scatter_by_phase(ax, rows, key, log_scale=False)
        ax.axhline(0.0, color="#666666", linestyle="--", linewidth=1.0)
        ax.set_title(title)
    axes[0].set_ylabel("active(final) - active(best)")
    fig.suptitle("Active drift from best to final", fontsize=14)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_share_drift_after_best(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(13.6, 4.6), sharey=True)
    for ax, key, title in zip(
        axes,
        ["share_0_drift", "share_1_drift", "share_2_drift"],
        ["layer 0", "layer 1", "layer 2"],
    ):
        _scatter_by_phase(ax, rows, key, log_scale=False)
        ax.axhline(0.0, color="#666666", linestyle="--", linewidth=1.0)
        ax.set_title(title)
    axes[0].set_ylabel("share(final) - share(best)")
    fig.suptitle("Active-share drift after best", fontsize=14)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_degradation_vs_layer2_share_drift(rows: Sequence[Dict], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7.8, 5.2))
    for phase in PHASES:
        group = [row for row in rows if row["phase"] == phase]
        if not group:
            continue
        ax.scatter(
            [row["share_2_drift"] for row in group],
            [max(row["final_minus_selected"], 1e-12) for row in group],
            s=62,
            color=PHASE_COLORS[phase],
            edgecolor="white",
            linewidth=0.6,
            label=phase,
        )
        for row in group:
            ax.annotate(
                f"s{row['seed']}",
                (row["share_2_drift"], max(row["final_minus_selected"], 1e-12)),
                xytext=(3, 3),
                textcoords="offset points",
                fontsize=7,
            )
    ax.axvline(0.0, color="#666666", linestyle="--", linewidth=1.0)
    ax.set_yscale("log")
    ax.set_xlabel("layer-2 share(final) - share(best)")
    ax.set_ylabel("final test loss - selected test loss")
    ax.set_title("Degradation vs layer-2 share drift")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def _trajectory_curve(metrics: Sequence[Dict[str, str]], key: str) -> np.ndarray:
    if key in {"train_loss", "val_loss", "test_loss", "param_count", "total_pruned"}:
        return np.array([float(metric[key]) for metric in metrics], dtype=float)
    if key.startswith("active_") or key.startswith("size_"):
        return np.array([float(metric[key]) for metric in metrics], dtype=float)
    raise ValueError(f"Unsupported trajectory key: {key}")


def _plot_phase_trajectory(
    rows: Sequence[Dict],
    metric_key: str,
    out_path: Path,
    title: str,
    ylabel: str,
    log_scale: bool = False,
    ylim: Optional[Tuple[float, float]] = None,
) -> None:
    fig, ax = plt.subplots(figsize=(8.2, 4.9))
    for phase in PHASES:
        group = [row for row in rows if row["phase"] == phase]
        if not group:
            continue
        curves = []
        epochs = None
        for row in group:
            metrics = read_csv(Path(row["run_path"]) / "metrics.csv")
            curves.append(_trajectory_curve(metrics, metric_key))
            if epochs is None:
                epochs = np.array([int(metric["epoch"]) for metric in metrics], dtype=int)
        curve_array = np.stack(curves, axis=0)
        q25 = np.quantile(curve_array, 0.25, axis=0)
        q50 = np.quantile(curve_array, 0.50, axis=0)
        q75 = np.quantile(curve_array, 0.75, axis=0)
        ax.plot(epochs, q50, color=PHASE_COLORS[phase], linewidth=2.0, label=phase)
        ax.fill_between(epochs, q25, q75, color=PHASE_COLORS[phase], alpha=0.18)
    if log_scale:
        ax.set_yscale("log")
    if ylim is not None:
        ax.set_ylim(*ylim)
    ax.set_xlabel("epoch")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_active_trajectories(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(13.6, 4.6), sharex=True)
    for layer_idx, ax in enumerate(axes):
        key = f"active_{layer_idx}"
        for phase in PHASES:
            group = [row for row in rows if row["phase"] == phase]
            if not group:
                continue
            curves = []
            epochs = None
            for row in group:
                metrics = read_csv(Path(row["run_path"]) / "metrics.csv")
                curves.append(_trajectory_curve(metrics, key))
                if epochs is None:
                    epochs = np.array([int(metric["epoch"]) for metric in metrics], dtype=int)
            curve_array = np.stack(curves, axis=0)
            q25 = np.quantile(curve_array, 0.25, axis=0)
            q50 = np.quantile(curve_array, 0.50, axis=0)
            q75 = np.quantile(curve_array, 0.75, axis=0)
            ax.plot(epochs, q50, color=PHASE_COLORS[phase], linewidth=2.0, label=phase)
            ax.fill_between(epochs, q25, q75, color=PHASE_COLORS[phase], alpha=0.18)
        ax.set_title(f"layer {layer_idx}")
        ax.set_xlabel("epoch")
        ax.grid(True, linestyle="--", alpha=0.3)
    axes[0].set_ylabel("active neurons")
    axes[2].legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_active_share_dynamics(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(13.6, 4.6), sharex=True, sharey=True)
    for layer_idx, ax in enumerate(axes):
        for phase in PHASES:
            group = [row for row in rows if row["phase"] == phase]
            if not group:
                continue
            curves = []
            epochs = None
            for row in group:
                metrics = read_csv(Path(row["run_path"]) / "metrics.csv")
                active = np.array(
                    [
                        [
                            int(metric["active_0"]),
                            int(metric["active_1"]),
                            int(metric["active_2"]),
                        ]
                        for metric in metrics
                    ],
                    dtype=float,
                )
                total_active = np.maximum(active.sum(axis=1, keepdims=True), 1.0)
                curves.append(active[:, layer_idx] / total_active[:, 0])
                if epochs is None:
                    epochs = np.array([int(metric["epoch"]) for metric in metrics], dtype=int)
            curve_array = np.stack(curves, axis=0)
            q25 = np.quantile(curve_array, 0.25, axis=0)
            q50 = np.quantile(curve_array, 0.50, axis=0)
            q75 = np.quantile(curve_array, 0.75, axis=0)
            ax.plot(epochs, q50, color=PHASE_COLORS[phase], linewidth=2.0, label=phase)
            ax.fill_between(epochs, q25, q75, color=PHASE_COLORS[phase], alpha=0.18)
        ax.set_ylim(0.0, 1.0)
        ax.set_title(f"layer {layer_idx}")
        ax.set_xlabel("epoch")
        ax.grid(True, linestyle="--", alpha=0.3)
    axes[0].set_ylabel("active share")
    axes[2].legend(fontsize=8)
    fig.suptitle("Active share dynamics by paired phase", fontsize=14)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_size_dynamics(rows: Sequence[Dict], out_path: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(13.6, 4.6), sharex=True, sharey=True)
    for layer_idx, ax in enumerate(axes):
        key = f"size_{layer_idx}"
        for phase in PHASES:
            group = [row for row in rows if row["phase"] == phase]
            if not group:
                continue
            curves = []
            epochs = None
            for row in group:
                metrics = read_csv(Path(row["run_path"]) / "metrics.csv")
                curves.append(_trajectory_curve(metrics, key))
                if epochs is None:
                    epochs = np.array([int(metric["epoch"]) for metric in metrics], dtype=int)
            curve_array = np.stack(curves, axis=0)
            q25 = np.quantile(curve_array, 0.25, axis=0)
            q50 = np.quantile(curve_array, 0.50, axis=0)
            q75 = np.quantile(curve_array, 0.75, axis=0)
            ax.plot(epochs, q50, color=PHASE_COLORS[phase], linewidth=2.0, label=phase)
            ax.fill_between(epochs, q25, q75, color=PHASE_COLORS[phase], alpha=0.18)
        ax.set_title(f"layer {layer_idx}")
        ax.set_xlabel("epoch")
        ax.grid(True, linestyle="--", alpha=0.3)
    axes[0].set_ylabel("physical size")
    axes[2].legend(fontsize=8)
    fig.suptitle("Size dynamics by paired phase", fontsize=14)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def write_readme(
    pattern_summary: Sequence[Dict],
    pairwise_stats: Sequence[Dict],
    out_path: Path,
    alignment_csv: Path,
) -> None:
    summary_by_phase = {row["phase"]: row for row in pattern_summary}
    stats_by_key = {(row["metric"], row["group_a"], row["group_b"]): row for row in pairwise_stats}
    lines = [
        "# Unpruned Phase Differentiation Study",
        "",
        "Data source:",
        "- fixed runs referenced by the alignment CSV",
        f"- grouped by the paired `prune_only` phase from `{alignment_csv}`",
        "",
        "Paired phase groups:",
        "- `prune0+2`: fixed runs whose same-seed `prune_only` run pruned layers 0 and 2",
        "- `prune0_only`: fixed runs whose same-seed `prune_only` run pruned only layer 0",
        "- `prune2_only`: fixed runs whose same-seed `prune_only` run pruned only layer 2",
        "- `no_prune`: fixed runs whose same-seed `prune_only` run never pruned",
        "",
        "Reading order:",
        "1. `primary/fixed_phase_assignments_by_seed.png`",
        "2. `primary/fixed_phase_endpoint_summary.png`",
        "3. `primary/fixed_phase_speed_summary.png`",
        "4. `primary/fixed_phase_best_to_final_degradation.png`",
        "5. `primary/fixed_phase_post_best_drift_rate.png`",
        "6. `primary/fixed_phase_degradation_vs_layer2_share_drift.png`",
        "7. `primary/fixed_phase_active_drift.png`",
        "8. `primary/fixed_phase_share_drift_after_best.png`",
        "9. `primary/fixed_phase_active_share_dynamics.png`",
        "10. `primary/fixed_phase_active_dynamics.png`",
        "11. `primary/fixed_phase_size_dynamics.png`",
        "12. `primary/fixed_phase_param_dynamics.png`",
        "13. `primary/fixed_phase_turnover_control.png`",
        "14. `supplementary/fixed_phase_test_loss_trajectories.png`",
        "15. `supplementary/fixed_phase_train_loss_trajectories.png`",
        "",
        "Pattern-level summary:",
    ]
    for phase in PHASES:
        row = summary_by_phase.get(phase)
        if row is None:
            continue
        lines.append(
            f"- {phase}: n={row['n']}, median selected={row['median_selected_test_loss']:.6g}, "
            f"median final={row['median_final_test_loss']:.6g}, median final-selected={row['median_final_minus_selected']:.6g}, "
            f"median best epoch={row['median_best_epoch']:.0f}, median final gap={row['median_final_test_train_gap']:.6g}"
        )
        lines.append(
            f"  median active@best=({row['median_active_0_best']:.1f}, {row['median_active_1_best']:.1f}, {row['median_active_2_best']:.1f}), "
            f"median active drift=({row['median_active_0_drift']:.1f}, {row['median_active_1_drift']:.1f}, {row['median_active_2_drift']:.1f})"
        )
        lines.append(
            f"  median share drift=({row['median_share_0_drift']:.4f}, {row['median_share_1_drift']:.4f}, {row['median_share_2_drift']:.4f}), "
            f"median drift rate={row['median_post_best_drift_rate']:.6g}"
        )
    contrast = stats_by_key.get(("final_test_loss", "prune0_only", "prune0+2"))
    prune2_contrast = stats_by_key.get(("final_test_loss", "prune2_only", "prune0_only"))
    no_prune_contrast = stats_by_key.get(("final_test_loss", "prune0_only", "no_prune"))
    lines.extend(
        [
            "",
            "Descriptive contrasts (median-based, no significance claims because sample sizes are tiny):",
        ]
    )
    if contrast is not None:
        lines.append(
            f"- `prune0_only - prune0+2` final test loss diff = {contrast['median_diff_a_minus_b']:.6g}"
        )
    if prune2_contrast is not None:
        lines.append(
            f"- `prune2_only - prune0_only` final test loss diff = {prune2_contrast['median_diff_a_minus_b']:.6g}"
        )
    if no_prune_contrast is not None:
        lines.append(
            f"- `prune0_only - no_prune` final test loss diff = {no_prune_contrast['median_diff_a_minus_b']:.6g}"
        )
    lines.extend(
        [
            "",
            "Interpretation:",
            "- These plots reuse the structural-phase lens on `fixed`, but the phase label now comes from the same-seed `prune_only` run rather than from actual pruning events inside the fixed run.",
            "- This means commit / first-prune plots are intentionally omitted here; they will only become meaningful after `shadow prune` logging exists for `fixed`.",
            "- If differences appear mainly in `final-selected`, drift, and generalization gap rather than in selected loss, that supports the idea that the paired phase label predicts late stability more than peak attainability.",
            "- The newly surfaced `prune2_only` group should be treated as a real discovered phase unless later sweeps show it collapses back into noise.",
            "",
            "Current limitations:",
            "- this is still a paired-label observational grouping, not a native `fixed` taxonomy yet",
            "- commit / first-prune style mechanism plots still require `shadow prune` logging inside `fixed`",
        ]
    )
    out_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    args = parse_args()
    out_dir = args.out_dir
    primary_dir = out_dir / "primary"
    supplementary_dir = out_dir / "supplementary"
    ensure_dirs([out_dir, primary_dir, supplementary_dir])
    rows = collect_rows(args.alignment_csv)
    pattern_summary = summarize_patterns(rows)
    pairwise_stats = build_pairwise_stats(rows)

    write_csv(out_dir / "fixed_phase_rows.csv", rows)
    write_csv(out_dir / "fixed_phase_summary.csv", pattern_summary)
    write_csv(out_dir / "fixed_phase_pairwise_stats.csv", pairwise_stats)

    plot_phase_assignments(rows, primary_dir / "fixed_phase_assignments_by_seed.png")
    plot_endpoint_panels(rows, primary_dir / "fixed_phase_endpoint_summary.png")
    plot_speed_panels(rows, primary_dir / "fixed_phase_speed_summary.png")
    plot_best_to_final_degradation(rows, primary_dir / "fixed_phase_best_to_final_degradation.png")
    plot_post_best_drift_rate(rows, primary_dir / "fixed_phase_post_best_drift_rate.png")
    plot_degradation_vs_layer2_share_drift(rows, primary_dir / "fixed_phase_degradation_vs_layer2_share_drift.png")
    plot_active_drift(rows, primary_dir / "fixed_phase_active_drift.png")
    plot_share_drift_after_best(rows, primary_dir / "fixed_phase_share_drift_after_best.png")
    plot_active_share_dynamics(rows, primary_dir / "fixed_phase_active_share_dynamics.png")
    plot_active_trajectories(rows, primary_dir / "fixed_phase_active_dynamics.png")
    plot_size_dynamics(rows, primary_dir / "fixed_phase_size_dynamics.png")
    _plot_phase_trajectory(
        rows,
        "param_count",
        primary_dir / "fixed_phase_param_dynamics.png",
        title="Parameter-count dynamics by paired phase",
        ylabel="parameter count",
        log_scale=False,
    )
    _plot_phase_trajectory(
        rows,
        "total_pruned",
        primary_dir / "fixed_phase_turnover_control.png",
        title="Turnover control: fixed runs stay structurally static",
        ylabel="total pruned per epoch",
        log_scale=False,
    )
    _plot_phase_trajectory(
        rows,
        "test_loss",
        supplementary_dir / "fixed_phase_test_loss_trajectories.png",
        title="Fixed test-loss trajectories by paired phase",
        ylabel="test loss",
        log_scale=True,
    )
    _plot_phase_trajectory(
        rows,
        "train_loss",
        supplementary_dir / "fixed_phase_train_loss_trajectories.png",
        title="Fixed train-loss trajectories by paired phase",
        ylabel="train loss",
        log_scale=True,
    )
    write_readme(pattern_summary, pairwise_stats, out_dir / "README.md", args.alignment_csv)


if __name__ == "__main__":
    main()
