import argparse
import csv
import shutil
from pathlib import Path
from typing import Dict, Iterable, List


FIXED_LINK_NAMES = [
    "active_neurons.png",
    "loss.png",
    "loss_log.png",
    "metrics.csv",
    "params.png",
    "sizes.png",
    "surface.png",
    "turnover.png",
    "config.json",
    "model.pt",
    "best_model.pt",
]

PRUNE_LINK_NAMES = [
    "active_neurons.png",
    "loss.png",
    "loss_log.png",
    "metrics.csv",
    "params.png",
    "sizes.png",
    "surface.png",
    "turnover.png",
    "config.json",
    "model.pt",
    "best_model.pt",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a browse-friendly tree of fixed runs grouped by paired prune_only phase."
    )
    parser.add_argument(
        "--alignment-csv",
        type=Path,
        default=Path(
            "research/analysis/studies/unpruned_phase_differentiation_20260316/phase_seed_alignment.csv"
        ),
        help="Seed-phase alignment CSV generated by build_unpruned_phase_alignment.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results/studies/unpruned_phase_differentiation_20260316/by_prune_phase"),
        help="Output directory for the grouped browse tree.",
    )
    return parser.parse_args()


def read_rows(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def ensure_clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def symlink_file(src: Path, dst: Path) -> None:
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    dst.symlink_to(src.resolve())


def symlink_run_files(run_dir: Path, out_dir: Path, prefix: str, names: Iterable[str]) -> None:
    for name in names:
        src = run_dir / name
        if not src.exists():
            continue
        symlink_file(src, out_dir / f"{prefix}_{name}")


def write_seed_readme(out_dir: Path, row: Dict[str, str]) -> None:
    lines = [
        f"# {row['prune_only_phase']} / seed_{row['seed']}",
        "",
        "## Run Links",
        f"- fixed run: `{row['fixed_run']}`",
        f"- prune_only run: `{row['prune_only_run']}`",
        "",
        "## Prune-Only Summary",
        f"- total pruned: {row['prune_only_total_pruned']}",
        f"- pruned_0 total: {row['prune_only_pruned_0_total']}",
        f"- pruned_1 total: {row['prune_only_pruned_1_total']}",
        f"- pruned_2 total: {row['prune_only_pruned_2_total']}",
        f"- selected test loss: {float(row['prune_only_selected_test_loss']):.6g}",
        f"- final test loss: {float(row['prune_only_final_test_loss']):.6g}",
        f"- final-selected: {float(row['prune_only_final_minus_selected']):.6g}",
        f"- best epoch: {row['prune_only_best_epoch']}",
        "",
        "## Fixed Summary",
        f"- selected test loss: {float(row['fixed_selected_test_loss']):.6g}",
        f"- final test loss: {float(row['fixed_final_test_loss']):.6g}",
        f"- final-selected: {float(row['fixed_final_minus_selected']):.6g}",
        f"- best epoch: {row['fixed_best_epoch']}",
        f"- final gap: {float(row['fixed_final_gap']):.6g}",
        f"- active drift: ({row['fixed_active_0_drift']}, {row['fixed_active_1_drift']}, {row['fixed_active_2_drift']})",
        "",
        "## Browse Files",
        "- `fixed_loss.png`, `fixed_loss_log.png`, `fixed_sizes.png`, `fixed_active_neurons.png`, `fixed_params.png`, `fixed_surface.png`, `fixed_turnover.png`",
        "- `prune_loss.png`, `prune_loss_log.png`, `prune_sizes.png`, `prune_active_neurons.png`, `prune_params.png`, `prune_surface.png`, `prune_turnover.png`",
        "- `fixed_run/` and `prune_run/` keep the full original run folders available as symlinks",
    ]
    (out_dir / "README.md").write_text("\n".join(lines))


def write_root_readme(out_dir: Path, rows: List[Dict[str, str]]) -> None:
    by_phase: Dict[str, List[Dict[str, str]]] = {}
    for row in rows:
        by_phase.setdefault(row["prune_only_phase"], []).append(row)

    lines = [
        "# Browse Fixed Runs By Paired Prune Phase",
        "",
        "This directory reorganizes `fixed` hard-task runs by the `prune_only` phase reached by the same seed.",
        "",
        "Layout:",
        "- `<phase>/seed_<k>/fixed_*.png` gives direct links to the fixed-run figures.",
        "- `<phase>/seed_<k>/prune_*.png` gives the paired prune-only figures for comparison.",
        "- `<phase>/seed_<k>/fixed_run/` and `<phase>/seed_<k>/prune_run/` link the full original run folders.",
        "",
        "Phase groups:",
    ]

    for phase in sorted(by_phase.keys()):
        seeds = ", ".join(f"seed_{row['seed']}" for row in sorted(by_phase[phase], key=lambda r: int(r["seed"])))
        lines.append(f"- {phase}: {seeds}")

    (out_dir / "README.md").write_text("\n".join(lines))


def build_tree(rows: List[Dict[str, str]], out_dir: Path) -> None:
    ensure_clean_dir(out_dir)
    write_root_readme(out_dir, rows)

    for row in rows:
        phase_dir = out_dir / row["prune_only_phase"]
        seed_dir = phase_dir / f"seed_{row['seed']}"
        seed_dir.mkdir(parents=True, exist_ok=True)

        fixed_run = Path(row["fixed_run"])
        prune_run = Path(row["prune_only_run"])

        symlink_file(fixed_run, seed_dir / "fixed_run")
        symlink_file(prune_run, seed_dir / "prune_run")
        symlink_run_files(fixed_run, seed_dir, "fixed", FIXED_LINK_NAMES)
        symlink_run_files(prune_run, seed_dir, "prune", PRUNE_LINK_NAMES)
        write_seed_readme(seed_dir, row)


def main() -> None:
    args = parse_args()
    rows = read_rows(args.alignment_csv)
    build_tree(rows, args.out_dir)


if __name__ == "__main__":
    main()
